"""统一事件枚举。

Core 通过事件把进度/状态传给前端（CLI），未来其它前端无需改业务逻辑。
"""
from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    JOB_STARTED = "JOB_STARTED"
    MINERU_SUBMITTED = "MINERU_SUBMITTED"
    MINERU_COMPLETED = "MINERU_COMPLETED"
    NORMALIZATION_STARTED = "NORMALIZATION_STARTED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    CHUNKING_COMPLETED = "CHUNKING_COMPLETED"
    TRANSLATION_STARTED = "TRANSLATION_STARTED"
    CHUNK_COMPLETED = "CHUNK_COMPLETED"
    RETRYING = "RETRYING"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
